language: perl

matrix:
  include:
# First group
    - perl: "5.30"
      dist: xenial
    - perl: "5.28"
      dist: xenial
    - perl: "5.20"
      dist: trusty
    - perl: "5.16"
      dist: trusty
    # The perl does not matter here, system perl will be used
    - perl: "5.18"
      os: osx
# Second group
    - perl: "5.22"
      dist: xenial
    - perl: "5.12"
      dist: trusty
    - perl: "5.10"
      dist: trusty
    - perl: "5.8"
      dist: trusty
    # Actually the perl here does not matter
    - perl: "5.14"
      env: USE_SYSTEM_PERL=1
      dist: precise
    # Actually the perl here does not matter
    - perl: "5.18"
      env: USE_SYSTEM_PERL=1
      dist: trusty
    # Actually the perl here does not matter
    - perl: "5.26"
      env: USE_SYSTEM_PERL=1
      dist: xenial

before_install:
 - if [ "$USE_SYSTEM_PERL" = 1 ]; then perlbrew off; fi

install:
 # cpanm is not available on MacOSX, so don't do anything here
 # see https://github.com/travis-ci/travis-ci/issues/2314
 # This works because this module has no dependencies
 #
 # On Linux run the normal travis-ci install command.
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cpanm --quiet --installdeps --notest .; fi

script:
 - perl Makefile.PL && env HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest

after_script:
  - make distcheck

branches:
  except:
    - /appveyor/
    - /github-actions/
    - /doozer/
sudo: false
