name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'
  pull_request:
  workflow_dispatch:

jobs:

  test_on_host:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       include:
         - os: 'ubuntu-22.04'
         - os: 'ubuntu-24.04'
         - os: 'windows-latest'
         - os: 'macos-latest'
    steps:
    - name: apt hacks
      # /etc/apt/sources.list should be sufficient; all the other repositories are possibly problematic
      run: |
        sudo rm -f /etc/apt/sources.list.d/*.list
        sudo apt-get update -qq
      if: "startsWith(matrix.os, 'ubuntu-')"
    - uses: taiki-e/checkout-action@v1

    - name: "perl dependency installation (ubuntu)"
      run: |
        sudo apt-get install -q --no-install-recommends cpanminus
        cpanm --sudo --quiet --notest --installdeps .
      if: "startsWith(matrix.os, 'ubuntu-')"
    - name: "perl dependency installation (macos)"
      run: |
        brew install cpanminus
        cpanm --sudo --quiet --notest --installdeps .
      if: "startsWith(matrix.os, 'macos-')"
    - name: "perl dependency installation (windows)"
      run: |
        cpanm --quiet --installdeps --notest .
      if: "startsWith(matrix.os, 'windows-')"

    - name: "Build and test (ubuntu + macos)"
      run: |
        set -e
        perl Makefile.PL
        make distcheck
        HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest
      if: "startsWith(matrix.os, 'ubuntu-') || startsWith(matrix.os, 'macos-')"
    - name: "Build and test (windows)"
      run: |
        c:\strawberry\perl\bin\perl Makefile.PL
        c:\strawberry\c\bin\gmake
        c:\strawberry\c\bin\gmake test
      if: "startsWith(matrix.os, 'windows-')"

  test_in_container_dists:
    name: Container tests with ${{ matrix.dist }}:${{ matrix.distver }}
    runs-on: ubuntu-latest
    container: ${{ matrix.dist }}:${{ matrix.distver }}
    strategy:
      matrix:
        include:
          - dist:    debian
            distver: jessie
          - dist:    debian
            distver: stretch
          - dist:    debian
            distver: buster
          - dist:    debian
            distver: bullseye
          - dist:    debian
            distver: bookworm
          - dist:    debian
            distver: trixie
          - dist:    fedora
            distver: 33
          - dist:    fedora
            distver: 40
          - dist:    rockylinux
            distver: 8
          - dist:    rockylinux
            distver: 9
          ## XXX disable until a mirrorlist replacement is found
          #- dist:    centos
          #  distver: 7
          - dist:    ubuntu
            distver: 16.04
          - dist:    ubuntu
            distver: 20.04
          - dist:    opensuse/tumbleweed
            distver: latest
          ## XXX very minimal system, misses even tar, so actions/checkout fails
          #- dist:    opensuse/leap
          #  distver: latest
    steps:
    - name: apt hacks
      run: |
        set -e
        CODENAME=$(perl -nle '/^VERSION_CODENAME="?([^"]+)/ and $codename=$1; /^VERSION="\d+ \((.*)\)/ and $maybe_codename=$1; END { print $codename || $maybe_codename }' /etc/os-release)
        case "$CODENAME" in
          wheezy|jessie|stretch)
            echo "APT::Get::AllowUnauthenticated 1;" > /etc/apt/apt.conf.d/02allow-unsigned
            echo "deb [check-valid-until=no] http://archive.debian.org/debian $CODENAME main"                   >  /etc/apt/sources.list
            echo "deb [check-valid-until=no] http://archive.debian.org/debian-security/ $CODENAME/updates main" >> /etc/apt/sources.list
            ;;
        esac
      if: "matrix.dist == 'debian' || matrix.dist == 'ubuntu'"
    # Run apt hacks before checkout-action, so the latter may install packages.
    - uses: taiki-e/checkout-action@v1
    - name: Install cpanminus on Debian
      run: |
        set -e
        apt-get update -qq
        apt-get install -q --no-install-recommends -y cpanminus make
      if: "matrix.dist == 'debian' || matrix.dist == 'ubuntu'"
    - name: Install cpanminus on Fedora
      env:
        DIST_DISTVER: "${{ matrix.dist }}:${{ matrix.distver }}"
      run: |
        set -e
        yum -y install perl-App-cpanminus
        if [ $DIST_DISTVER = "centos:7" ]
        then
          yum -y install "perl(Test::More)" "perl(CPAN)"
        fi
      if: "matrix.dist == 'fedora' || matrix.dist == 'centos' || matrix.dist == 'rockylinux'"
    - name: Install perl and more on OpenSUSE
      run: |
        set -e
        zypper install -y make perl perl-App-cpanminus lsb-release
      if: "matrix.dist == 'opensuse/tumbleweed' || matrix.dist == 'opensuse/leap'"
    - name: Build and test
      run: |
        set -e
        cpanm --sudo --quiet --notest --installdeps .
        perl Makefile.PL
        make distcheck
        HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest
      if: "!startsWith(matrix.os,'windows-')"

  test_in_container_perls:
    name: Test with perl ${{ matrix.perlimage }}
    runs-on: ubuntu-latest
    container: perl:${{ matrix.perlimage }}
    strategy:
      matrix:
        include:
          - perlimage: 5.8.9-threaded-stretch
          - perlimage: 5.10.1-buster
          - perlimage: 5.12.5-stretch
          - perlimage: 5.14.4-stretch
          - perlimage: 5.16.3-buster
          - perlimage: 5.18.4-buster
          - perlimage: 5.22.4-stretch
          - perlimage: 5.36.0-slim-bullseye
          - perlimage: 5.38.0-slim-bookworm
          - perlimage: 5.40.0-slim-bookworm
          - perlimage: 5.42.0-slim-bookworm

    steps:
    - uses: taiki-e/checkout-action@v1
    - name: "build and test"
      run: |
        cpanm --quiet --installdeps --notest .
        perl Makefile.PL
        make distcheck
        HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest

  test_freebsd:
    name: Test on FreeBSD ${{ matrix.osvers }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - osvers: '13.4'
          - osvers: '14.2'
    steps:
    - uses: actions/checkout@v4
      with:
        clean: false
        show-progress: false
    - uses: cross-platform-actions/action@v0.26.0
      with:
        operating_system: freebsd
        version: '${{ matrix.osvers }}'
        run: |
          sudo pkg update
          sudo pkg install -y perl5
          perl Makefile.PL
          make
          make test

  test_openbsd:
    name: Test on OpenBSD ${{ matrix.osvers }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - osvers: 7.4
    steps:
    - uses: actions/checkout@v4
      with:
        clean: false
        show-progress: false
    - uses: cross-platform-actions/action@v0.26.0
      with:
        operating_system: openbsd
        version: '${{ matrix.osvers }}'
        # note: "doas" is usually preferred over "sudo" in OpenBSD, but atm not available, see https://github.com/cross-platform-actions/action/issues/75
        run: |
          sudo pkg_add -u 
          sudo pkg_add -i perl
          perl Makefile.PL
          make
          make test
